// Generated by https://quicktype.io

export interface DameJIdloResponse {
  status_code: number;
  message: string;
  data: Data;
}

export interface Data {
  available_count: number;
  returned_count: number;
  events: unknown[];
  close_reasons: unknown[];
  banner: string;
  items: Restaurant[];
  num_platform_delivery: number;
  num_vendor_delivery: number;
  num_platform_delivery_page: number;
  num_vendor_delivery_page: number;
  dynamic_pricing_session: null;
  discount_labels_metadata: DiscountLabelsMetadata;
  aggregations: Aggregations;
  tags: DiscountLabelsMetadata;
}

export interface Aggregations {
  cuisines: FoodCharacteristicElement[];
  events: unknown[];
  discount_labels: unknown[];
  discounts: unknown[];
  close_reasons: unknown[];
  banner: string;
  location_event: null;
  partners: unknown[];
  payment_types: PaymentType[];
  foodCharacteristics: FoodCharacteristicElement[];
  quickFilters: FoodCharacteristicElement[];
  foodCharacteristicsTypes: FoodCharacteristicsTypes;
}

export interface FoodCharacteristicElement {
  id: number;
  title: string;
  count: number;
  slug?: null | string;
  type?: string;
}

export interface FoodCharacteristicsTypes {
  promo: FoodCharacteristicElement[];
  "": FoodCharacteristicElement[];
  typy_jidel: FoodCharacteristicElement[];
  diety: FoodCharacteristicElement[];
  napoje: FoodCharacteristicElement[];
}

export interface PaymentType {
  id: string;
  title: string;
  highlighted: boolean;
  count: number;
}

export type DiscountLabelsMetadata = unknown;

export interface Restaurant {
  id: number;
  avg_rating?: string;
  code: string;
  accepts_instructions: boolean;
  address: string;
  address_line2: string;
  budget: number;
  chain: Chain;
  city: City;
  cuisines: PrimaryCuisineElement[];
  custom_location_url: string;
  customer_type: string;
  delivery_box: string;
  delivery_fee_type: string;
  description: string;
  distance: number;
  food_characteristics: FoodCharacteristic[];
  has_delivery_provider: boolean;
  hero_image: string;
  hero_listing_image: string;
  is_new_until: string;
  premium_position: number;
  latitude: number;
  logo: string;
  longitude: number;
  loyalty_percentage_amount: number;
  loyalty_program_enabled: boolean;
  maximum_express_order_amount: number;
  metadata: Metadata;
  original_delivery_fee: number;
  minimum_delivery_fee: number;
  minimum_delivery_time: number;
  minimum_order_amount: number;
  minimum_pickup_time: number;
  name: string;
  payment_types: unknown[];
  post_code: string;
  primary_cuisine_id: number;
  rating: number;
  redirection_url: string;
  review_number: number;
  review_with_comment_number: number;
  score: number;
  service_fee_percentage_amount: number;
  service_tax_percentage_amount: number;
  tag: string;
  tags: Tag[];
  url_key: string;
  vat_percentage_amount: number;
  characteristics: Characteristics;
  vendor_points: number;
  vertical: string;
  vertical_segment: string;
  vertical_parent: string;
  web_path: string;
  website: string;
  has_online_payment: boolean;
  discounts_info: DiscountsInfo[];
  discounts: unknown[];
  vendor_legal_information: VendorLegalInformation;
  disclaimers: unknown[];
  customer_phone: string;
  vertical_type_ids: string[];
  delivery_provider: string;
  is_active: boolean;
  is_best_in_city: boolean;
  is_checkout_comment_enabled: boolean;
  is_delivery_enabled: boolean;
  is_new: boolean;
  is_pickup_enabled: boolean;
  is_premium: boolean;
  is_preorder_enabled: boolean;
  is_promoted: boolean;
  is_replacement_dish_enabled: boolean;
  is_service_fee_enabled: boolean;
  is_service_tax_enabled: boolean;
  is_service_tax_visible: boolean;
  is_test: boolean;
  is_vat_disabled: boolean;
  is_vat_included_in_product_price: boolean;
  is_vat_visible: boolean;
  is_voucher_enabled: boolean;
  ncr_pricing_model: string;
  tag_ids: unknown[];
}

export interface Chain {
  code: string;
  name: string;
  main_vendor_code: string;
  url_key: string;
}

export interface Characteristics {
  cuisines: PrimaryCuisineElement[];
  food_characteristics: FoodCharacteristic[];
  primary_cuisine: PrimaryCuisineElement;
}

export interface PrimaryCuisineElement {
  id: number;
  name: string;
  url_key: string;
  main: boolean;
}

export interface FoodCharacteristic {
  id: number;
  name: string;
  is_halal: boolean;
  is_vegetarian: boolean;
}

export interface City {
  name: string;
}

export interface DiscountsInfo {
  id: string;
  value: number;
}

export interface Metadata {
  has_discount: boolean;
  timezone: string;
  close_reasons: unknown[];
  available_in: null;
  events: unknown[];
  is_delivery_available: boolean;
  is_pickup_available: boolean;
  is_dine_in_available: boolean;
  is_express_delivery_available: boolean;
  is_temporary_closed: boolean;
  is_flood_feature_closed: boolean;
}

export interface Tag {
  code: string;
  text: string;
}

export interface VendorLegalInformation {
  legal_name: string;
  trade_register_number: string;
}
